# Generated by Django 3.2.7 on 2021-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('#E26C2D', 'Оранжевый'), ('#49B64E', 'Зелёный'), ('#8775D2', 'Фиолетовый')], max_length=7, verbose_name='цвет'),
        ),
    ]
