# Generated by Django 3.2.7 on 2021-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/%Y/%m/%d/', verbose_name='изображение')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('text', models.TextField(verbose_name='текст')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='время приготовления')),
                ('is_favorited', models.BooleanField(default=False, verbose_name='в избранном')),
                ('is_in_shopping_cart', models.BooleanField(default=False, verbose_name='в списке покупок')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
            },
        ),
    ]
