# Generated by Django 3.2.7 on 2021-09-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210925_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/media/%Y/%m/%d/', verbose_name='изображение'),
        ),
    ]
