# Generated by Django 3.2.7 on 2021-09-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='количество'),
        ),
    ]
